[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "distribution"
version = "0.0.1"
description = "Data Fusion Contest 2025 - Task # 3: https://ods.ai/competitions/data-fusion2025-distribution"
authors = [
  { name = "Alexander Mikhailov" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.10"

[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[tool.ruff.lint.isort]
known_first_party = ["distribution"]
force_sort_within_sections = true
